apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret-{{ .Release.Name }}  # Unique name for each release
type: Opaque
data:
  user: {{ .Values.rabbitmq.user | b64enc | quote }}
  password: {{ .Values.rabbitmq.password | b64enc | quote }}
