replicaCount: 1

image:
  repository: kbudde/rabbitmq-exporter
  tag: v0.29.0
  pullPolicy: Always
# Producer and Consumer Image
consumer_image:
  repository: tsofnatg/consumer  # Your consumer image
  tag: latest                    # Tag for the consumer image
  pullPolicy: Always

producer_image:
  repository: tsofnatg/producer  # Your producer image
  tag: latest                    # Tag for the producer image
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9419

rabbitmq:
  url: http://rabbitmq:15672
  #user: tsofnat
  #password: Guliguli1
  capabilities: bert,no_sort
  include_queues: ".*"
  include_vhost: ".*"
  skip_queues: "^$"
  skip_verify: "false"
  skip_vhost: "^$"
  exporters: "exchange,node,overview,queue"
  output_format: "TTY"
  timeout: 30
  max_queues: 20
  excludeMetrics: ""
  connection: "direct"
serviceAccount:
  create: true
ingress:
  enabled: false
hpa:
  enabled: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80